services:
  paydle:
    build: .
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  default:
    name: paydle
    driver: bridge
volumes:
  mysql-data: